[project]
name = "tic-tac-toe-game"
description = "Judi Tic tac toe on Stacks blockchain"
authors = ["Your Name <your.email@example.com>"]
telemetry = true
cache_dir = "./.clarinet"

[contracts.tic-tac-toe-satu]
path = "contracts/tic-tac-toe-satu.clar"
clarity_version = 2
epoch = 2.4

[repl]
costs_version = 2
parser_version = 2